version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: sleeptracker-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sleeptrackerdb
  app:
    build: .
    container_name: sleeptrackerapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/sleeptrackerdb
    depends_on:
      - mongo
